import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '/dashboard/main',
    title: 'All Pages',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: '/extra-pages/invoice',
        title: 'Create Invoice',
        iconType: 'material-icons-two-tone',
        icon: 'fact_check',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
          
      },
      {
        path: '/extra-pages/invoice_view',
        title: 'Invoice View',
        iconType: 'material-icons-two-tone',
        icon: 'fact_check',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
          
      },
      {
        path: '/extra-pages/pricing_level',
        title: 'Pricing Level',
        iconType: 'material-icons-two-tone',
        icon: 'fact_check',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
          
      },
      {
        path: '/extra-pages/offering_level',
        title: 'Offering Level',
        iconType: 'material-icons-two-tone',
        icon: 'fact_check',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
          
      },
      {
        path: '/extra-pages/purchase_level',
        title: 'Purchase Level',
        iconType: 'material-icons-two-tone',
        icon: 'fact_check',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
          
      },
      {
        path: '/extra-pages/invoicelist',
        title: 'Invoice Reports',
        iconType: 'material-icons-two-tone',
        icon: 'description',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
          
      },
      {
        path: '/extra-pages/userprofile',
        title: 'Your Items',
        iconType: 'material-icons-two-tone',
        icon: 'timeline',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
          
      },
      {
        path: '/extra-pages/user',
        title: 'All Users',
        iconType: 'material-icons-two-tone',
        icon: 'face',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
          
      },
    ],
      
  },
 
  
 
];


// export const ROUTES: RouteInfo[] = [
//   {
//     path: '',
//     title: '-- Main',
//     iconType: '',
//     icon: '',
//     class: '',
//     groupTitle: true,
//     badge: '',
//     badgeClass: '',
//     submenu: [],
//   },
// 
//   {
//     path: '',
//     title: '-- Apps',
//     iconType: '',
//     icon: '',
//     class: '',
//     groupTitle: true,
//     badge: '',
//     badgeClass: '',
//     submenu: [],
//   },
//   
//   {
//     path: '',
//     title: 'Email',
//     iconType: 'material-icons-two-tone',
//     icon: 'email',
//     class: 'menu-toggle',
//     groupTitle: false,
//     badge: '3',
//     badgeClass: 'badge bg-orange sidebar-badge float-end',
//     submenu: [
//       {
//         path: '/email/inbox',
//         title: 'Inbox',
//         iconType: '',
//         icon: '',
//         class: 'ml-menu',
//         groupTitle: false,
//         badge: '',
//         badgeClass: '',
//         submenu: [],
//       },
//       {
//         path: '/email/compose',
//         title: 'Compose',
//         iconType: '',
//         icon: '',
//         class: 'ml-menu',
//         groupTitle: false,
//         badge: '',
//         badgeClass: '',
//         submenu: [],
//       },
//       {
//         path: '/email/read-mail',
//         title: 'Read Email',
//         iconType: '',
//         icon: '',
//         class: 'ml-menu',
//         groupTitle: false,
//         badge: '',
//         badgeClass: '',
//         submenu: [],
//       },
//     ],
//   },
//   
//   {
//     path: '',
//     title: 'Multi level Menu',
//     iconType: 'material-icons-two-tone',
//     icon: 'slideshow',
//     class: 'menu-toggle',
//     groupTitle: false,
//     badge: '',
//     badgeClass: '',
//     submenu: [
//       {
//         path: '/multilevel/first1',
//         title: 'First',
//         iconType: '',
//         icon: '',
//         class: 'ml-menu',
//         groupTitle: false,
//         badge: '',
//         badgeClass: '',
//         submenu: [],
//       },
//       {
//         path: '/',
//         title: 'Second',
//         iconType: '',
//         icon: '',
//         class: 'ml-sub-menu',
//         groupTitle: false,
//         badge: '',
//         badgeClass: '',
//         submenu: [
//           {
//             path: '/multilevel/secondlevel/second1',
//             title: 'Second 1',
//             iconType: '',
//             icon: '',
//             class: 'ml-menu2',
//             groupTitle: false,
//             badge: '',
//             badgeClass: '',
//             submenu: [],
//           },
//           {
//             path: '/',
//             title: 'Second 2',
//             iconType: '',
//             icon: '',
//             class: 'ml-sub-menu2',
//             groupTitle: false,
//             badge: '',
//             badgeClass: '',
//             submenu: [
//               {
//                 path: '/multilevel/thirdlevel/third1',
//                 title: 'third 1',
//                 iconType: '',
//                 icon: '',
//                 class: 'ml-menu3',
//                 groupTitle: false,
//                 badge: '',
//                 badgeClass: '',
//                 submenu: [],
//               },
//             ],
//           },
//         ],
//       },
//       {
//         path: '/multilevel/first3',
//         title: 'Third',
//         iconType: '',
//         icon: '',
//         class: 'ml-menu',
//         groupTitle: false,
//         badge: '',
//         badgeClass: '',
//         submenu: [],
//       },
//     ],
//   },
// ];
